# settings.yaml

Screen_Height: 720
Screen_Width: 1280

Fullscreen: False

# this is a comment
# please do not remove any settings, you can change settings. You can add settings but they wont be used. Altough its not recommended to add any.