# settings.yaml

Screen_Height: 1080
Screen_Width: 1920

Fullscreen: True
Hardware_Accel: True

# this is a comment
# please do not remove any settings, you can change settings. You can add settings but they wont be used. Altough its not recommended to add any.